version: 2

models:
  - name: stg_sales
    columns:
      - name: sale_id
        data_tests: [not_null, unique]
      - name: product_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_products')
                field: product_id
      - name: sales_amount
        data_tests: [not_null]

  - name: stg_products
    columns:
      - name: product_id
        data_tests: [not_null, unique]
      - name: product_name
        data_tests: [not_null]